#zf190712.1156

version: '3.3'

services:
    db:
#        image: mysql:5.7
        image: mariadb
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root!
            MYSQL_DATABASE: db1
            MYSQL_USER: userdb1
            MYSQL_PASSWORD: userdb1!
        ports:
            - "3306:3306"


    nas:
        image: itsthenetwork/nfs-server-alpine:latest
        volumes:
            - ./nfs_share:/nfsshare
        restart: always
        environment:
            SHARED_DIRECTORY: /nfsshare
        ports:
            - "2049:2049"
        privileged: true



#docker run -d -p 2049:2049 --name nfs --privileged -v $1:/nfsshare -e SHARED_DIRECTORY=/nfsshare 
#itsthenetwork/nfs-server-alpine:latest
