#zf190712.1123

version: '3.3'

services:
    db:
#        image: mysql:5.7
        image: mariadb
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root!
            MYSQL_DATABASE: db1
            MYSQL_USER: userdb1
            MYSQL_PASSWORD: userdb1!
        ports:
            - "3306:3306"

            

