#zf190718.1024
#cp190717.1632

#source: https://stackoverflow.com/questions/39204142/docker-compose-with-multiple-databases


version: '3.3'

volumes:
    db:
        driver: local

services:
    db:
        image: mysql:5.7
#        image: mariadb
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root!
#            MYSQL_DATABASE: db1
#            MYSQL_USER: userdb1
#            MYSQL_PASSWORD: userdb1!
        ports:
            - "3306:3306"


    nas:
        image: itsthenetwork/nfs-server-alpine:latest
        volumes:
            - ./nfs_share:/nfsshare
        restart: always
        environment:
            SHARED_DIRECTORY: /nfsshare
        ports:
            - "2049:2049"
        privileged: true

